language: python
python:
- 2.7
before_install:
  - rvm install 2.2.5
install:
- pip install --upgrade setuptools
- pip install coveralls
script:
- python setup.py test
after_success:
- coverage run --source=heralding setup.py -q nosetests
- coveralls
deploy:
  provider: pypi
  user: Johnny.Vestergaard
  password:
    secure: LLP/6dscaN6mI5wQYvuwhbOhpFrMtXa9eUz2HLSltFR+x5RN5agli0PFZaGJLRl+AneMbJy7+LwNSpNpiLX04ksAcl6ZO5boGQLeQbs5mQKURVlyLHL4848cp+Jy6K6xfFRePh6KBHslfEJU9YBWtzVCfrYEazYJMASLsQ8VL+zfJ8ZT8uzIzKe2EraN6nyqEpTZTCQMS3FCYPg6MGneHSm9AK5pXBjN1YuN3yggLVhYFJLtjqpwgLwj3xBQptdjZ4hGQ4ZS30ZpJVZ7IAM6uYXrTExWVbL+dIXlanzmUW2HaPyNKaosBwQkMxkouWaXylqzSZMklCZc1wXnBLs4BTYPVG4sbzer3kb8dPqnnCPkTrO2mTJtdmrwH9t1M5kGpx0U9x1s997CvvtwQJ2C8+cvy9W8+m5fzJIzUBrbUlMYzsb+N3qUjP+uzrUB1SFlJFSytFSHeJ6jQnpj3fFO99wyqlkO1ifE+kU9FXm1+Pb2g/EqRUfwrVQ/IdJYN2czq1li2E6meIanmAIWFsv91RdaAHgShyBU6q59b4LiBaAIrNmRZukehKu0Ub5xO5/1k6CY10dVlvjSAM0/0K8JKpIY2CSBfFxao4pi27qkHIe+78fZbF4l7DRIG5b3yxJcZnQizBQynzI7m8WKelQp8nHmtIWkv52ddjMznck6pAM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: johnnykv/heralding
    condition: $TRAVIS_TAG =~ ^Release_[0-9]+[.][0-9]+[.][0-9]+
